### ISSUE TITLE
Add another account

### ISSUE THREAD

**Issue by baronfortesque** [MrEliasen/twitch-bot-list#2] opened 2019-08-10 10:04 UTC
# What is this issue about?

- [X] Add an account
- [ ] Remove an account 

### Twitch Account

Please enter the name of the Twitch.tv account(s) in question:

### Reason for adding or removing from list:

Please provide as many details and "evidence" as possible.

All have things on their twitch panels saying either that they lurk, watch other streams and will host you in raffles. They also never said a word in my stream and they always are there!

**Comment by MrEliasen** [comment] 2019-08-10 10:19
I assume this is a duplicate of your initial issue. I will close it, but feel free to make a new issue if you have other bots you wish to add!

Thanks!

**Closed by MrEliasen** 2019-08-10 10:19 UTC

**Comment by baronfortesque** [comment] 2019-08-10 11:17
Oh something went wrong then. Added 3 more bots there... will do it again.

**Comment by MrEliasen** [comment] 2019-08-10 11:18
No problem! Feel free to add multiple per issue if you wish, just separate the evidence per bot so i can further investigate :).

Thanks for contributing!
